### ISSUE TITLE
Reindex search from CLI?

### ISSUE THREAD

**Issue by ShonM** [scragg0x/realms-wiki#103]
I don't at all understand how to run this: https://github.com/scragg0x/realms-wiki/blob/853630646e026c0437d63459a8df05f80cd23413/realms/modules/search/commands.py#L13

From usage, I see pages are populated in the search index when edited, but I can't for the life of me figure out how to repopulate the search index with the entire wiki contents. I can't find a CLI command or even really see how this is supposed to be run. I am also brand new to Python and virtualenv :)

Everything is working great aside from this. Moved a ~100 page Gollum wiki with directories an hour ago with little trouble and very impressed so far. A huge thank you to everyone involved!

**Comment by gazpachoking** [comment]
You should be able to run `realms-wiki search rebuild_index`. Seems there is a bug at the moment though and that's not accessible from cli. #159 should fix it
