### ISSUE TITLE
(Update Pip Package) Unable to create Subdirs on Realms with Docker

### ISSUE THREAD

**Issue by antonizoon** [scragg0x/realms-wiki#129]
After pulling the latest docker image, I've set up Realms and it works great.

However, I cannot create subfolders or pages under them for some reason. I was able to create them in realms.io just by specifying the path in the page name:

http://realms.io/folder/test

However, on my docker instance, this simply returns Page Not Found, and when I use / in the names, they simply get filtered out. Maybe the version of Realms pulled by docker is older?

Also, how do I configure a PostgreSQL database if I use Realms with Docker?

**Comment by antonizoon** [comment]
It looks like the pip package of Realms is just really old. Maybe it should be updated.

**Comment by scragg0x** [comment]
I just updated pip and docker builds.
