### ISSUE TITLE
Realms does not respect database config

### ISSUE THREAD

**Issue by nakato** [scragg0x/realms-wiki#137]
Using the `realms-wiki.json` that `realms-wiki setup` generates, I set `DB_URI` as `mysql+mysqldb://realms:QWERTY@127.0.0.1/realms`, however a sqlite database is generated at `/tmp/realms.db`.

The expected outcome is `/tmp/realms.db` is not created and the database is used from what is set at DB_URI.

A temporary workaround is setting the `SQLALCHEMY_DATABASE_URI` to the same string as `DB_URI` in `realms-wiki.json`

This is caused by `SQLALCHEMY_DATABASE_URI = DB_URI`, when `DB_URI` updates, `SQLALCHEMY_DATABASE_URI` remains set to the value DB_URI was previously.

**Comment by ghtyrant** [comment]
Can confirm. Workaround works, thanks!
