### ISSUE TITLE
Authentication Bypass: Anon can read/edit/create anything on private wiki

### ISSUE THREAD

**Issue by Javantea** [scragg0x/realms-wiki#182]
With a config set:

```
{
    "ALLOW_ANON": true,
    "PRIVATE_WIKI": true
    "REGISTRATION_ENABLED": true,
}
```
A login page appears for non-authenticated users on many pages, viewing, history, index.

However the /_create and /_edit paths both show data and are writable.

Anon can edit/update/read/create anything if Anon knows the path. This is caused by using @login_required but not 
```
if current_app.config.get('PRIVATE_WIKI') and current_user.is_anonymous:
    return current_app.login_manager.unauthorized()
```
in the functions edit and create. Allowing anonymous on a private wiki causes an inconsistent authentication mechanism on Realms Wiki.

**Comment by gazpachoking** [comment]
Basically, you are thinking ALLOW_ANON should be ignored when PRIVATE_WIKI is set? That makes sense to me. Would just making [this function](https://github.com/scragg0x/realms-wiki/blob/8a5cfbb2d88e461e0d5b45a77c5710940c105ab9/realms/config/__init__.py#L126) return `not self.PRIVATE_WIKI and self.ALLOW_ANON` do it?
