### ISSUE TITLE
Namespaces/Tags/Categories

### ISSUE THREAD

**Issue by ghtyrant** [scragg0x/realms-wiki#35]
Do you plan on implementing namespaces (or similar features like tags or categories)?
Wikis with a lot of pages can get quite messy if everything is in the same namespace.

Using sub folders in the base git repository would be the easiest way to achieve some sort of categories/namespaces, although limiting the flexibility by allowing a page to be in one category only. But imho it's the only way to reproduce the wiki's structure in the file system.

Storing this information in a page's metadata on the other hand forces realms to look into each file - meh.

What are your thoughts on this?

**Comment by gazpachoking** [comment]
:+1: for namespaces

**Comment by gazpachoking** [comment]
I implemented subdirs in #86. Testing and feedback are welcomed.

**Comment by scragg0x** [comment]
I merged the PR and did another commit.  There is still one issue I have to look at.  Dulwich is wigging out.

```
  File "/home/vagrant/.venv/lib/python2.7/site-packages/dulwich/objects.py", line 833, in __init__
    super(Tree, self).__init__()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by gazpachoking** [comment]
@scragg0x Hmm, how did you get that?

**Comment by gazpachoking** [comment]
Can we close this now? @scragg0x ?

**Comment by scragg0x** [comment]
Yeah
