### ISSUE TITLE
Delete a page

### ISSUE THREAD

**Issue by loleg** [scragg0x/realms-wiki#39]
This would be quite important for keeping things sane, since renaming a page clones it, and things are flat now. Yes, deleting via git seems to work fine (any issues to watch out for?) Yes, the question of undelete will come up (a log filter trashcan?) But, nonfunctioning buttons do not inspire user trust.

**Comment by scragg0x** [comment]
More on that here: https://github.com/scragg0x/realms-wiki/issues/61
I will look at this.
