### ISSUE TITLE
Manage subpages

### ISSUE THREAD

**Issue by CristianCantoro** [scragg0x/realms-wiki#50]
It would be nice to manage subpages and/or subdirectories with realms-wiki.
E.g.: `http://realms.io/asdf` is a page and `http://realms.io/asdf/subpage` would be a subpage.

C

**Comment by theherk** [comment]
It looks like it has the routing set up right, but the pages are not found. For example, if I create a file `test/test.md` at the root, the search does find the file. The link leads to the address /test/test, but says "Page Not Found".

**Comment by phutchins** [comment]
I see this too. Is this still being maintained? I've forked and plan to fix this issue, or add the feature if it's not an actual bug.

**Comment by scragg0x** [comment]
I didn't implement subpages because I was setting a simple goal.  I would very much like this to be a feature.

**Comment by phutchins** [comment]
Awesome. Might see if I can devote some time to creating a merge request.

**Comment by steveeJ** [comment]
Are there plans to make this happen? This feature would be a great step forward in usability.

**Comment by gazpachoking** [comment]
:+1: Trying to find something to migrate our trac wiki to, and subpages are a must for us.

**Comment by gazpachoking** [comment]
I had a go to see how hard this would be and it seems like it's at least most of the way already with #86

**Comment by scragg0x** [comment]
Duplicate and also nearly complete and deployed soon.
