### ISSUE TITLE
Question about encode format

### ISSUE THREAD

**Issue by magic890** [scragg0x/realms-wiki#59]
I'm wondering why you are using `latin-1` encode on https://github.com/scragg0x/realms-wiki/blame/master/realms/modules/wiki/models.py#L180-L181 or https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/wiki/models.py#L66 instead of `UTF8`.

I know that it is smaller for store data, but it is not so wider in character encoding as `UTF8`.

There is any particular reason?

**Comment by scragg0x** [comment]
UTF-8 should be fine assuming gittle is ok with it.  In this case, it shouldn't matter because one is a sha1 and other is filename which is restricted to match a URL friendly name (the canonical name).

**Comment by magic890** [comment]
Thank you for the clarification.
