### ISSUE TITLE
User's setting page blank

### ISSUE THREAD

**Issue by magic890** [scragg0x/realms-wiki#62]
I'm wondering why the user's setting page is blank (also on your demo on [http://realms.io](http://realms.io)).

Reading the source code, I guess that something has to be printed on the page. Supposed stack trace:

1. [modules/auth/views.py](https://github.com/scragg0x/realms-wiki/blob/master/realms/modules/auth/views.py#L66)
2. [templates/auth/settings.html](https://github.com/scragg0x/realms-wiki/blob/master/realms/templates/auth/settings.html#L2)
3. [templates/macros.html](https://github.com/scragg0x/realms-wiki/blob/master/realms/templates/macros.html)

**Comment by scragg0x** [comment]
It was going to be a place holder for user related switches.  I may get rid of the link until it has something useful.

**Comment by magic890** [comment]
Maybe it could be used to place a theme selector.

I've also noticed that switching theme do not persist for the user. In fact, if you reload the page, the default theme will be displayed.

**Comment by scragg0x** [comment]
> Maybe it could be used to place a theme selector.

That's a good idea

> I've also noticed that switching theme do not persist for the user. In fact, if you reload the page, the default theme will be displayed.

hmm, I could of sworn it worked before.  I will make a separate bug issue.
