### ISSUE TITLE
Changing CSS for tables

### ISSUE THREAD

**Issue by zeigerpuppy** [scragg0x/realms-wiki#72]
table rendering doesn't have any space between columns, is there a way to fix this in the CSS?
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

![2015-08-30 10 25 46 pm](https://cloud.githubusercontent.com/assets/415981/9567215/1f47393c-4f66-11e5-86b2-137ce271f93b.jpg)

**Comment by scragg0x** [comment]
It appears the alignment isn't working.  I suppose this is a limitation of the marked parser.  I may into using something else if it's better.  I added the classes `table` and `table-bordered` by default.

**Comment by scragg0x** [comment]
http://realms.io/_edit/table-test
