### ISSUE TITLE
Manual git updates and cache

### ISSUE THREAD

**Issue by gazpachoking** [scragg0x/realms-wiki#98]
Now that the cache is working for pages, is there some sort of call that would update or invalidate the cache in case the git repo was updated from outside realms? (maybe this is something we could add to commands.py if there isn't currently a way?)  I'm thinking of having some sort of 2 way sync to github once I get our realms instance live, such that we could accept PRs in github which get merged into the realms repo.

**Comment by scragg0x** [comment]
I believe git repos support commit hooks that can run a script.  You can run a cli command to invalidate cache.  Realms dont have a cmd yet but that should be easy.  
With github, a hook to make a request to realms would work.

**Comment by gazpachoking** [comment]
Yeah, I was thinking a post-merge hook, but then I was wondering if dulwich would also trigger that from realms updates? I can fit it into a script one way or another, was just wondering if you agreed a new realms command was the thing to do. I'll look into adding one when I get some time if you don't.

**Comment by scragg0x** [comment]
I agree, it's a good feature and having a command available is good regardless.
